apiVersion: apps/v1
kind: Deployment
metadata:
 
  labels:
    app: flaskdemo
  name: flaskdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskdemo

  strategy: {}
  template:
    metadata:
      #creationTimestamp: null
      labels:
        app: flaskdemo
    spec:
      containers:
      - image: 22nit/flaskcicd:latest
        name: flaskdemo
        resources: {}
        
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flask-lb-service
  labels:
    app: fask-lb-service

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemo
